//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarquesasServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarquesasServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquesas Server.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marquesas Server has been started succesfully! To visit the Admin page select Tools-&gt;Marquesas Server Admin. To visit the index page click OK below..
        /// </summary>
        internal static string FirstTimeRun {
            get {
                return ResourceManager.GetString("FirstTimeRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///  &lt;head&gt;
        ///    &lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;
        ///    &lt;title&gt;Marquesas Javascript Examples&lt;/title&gt;
        ///  &lt;/head&gt;
        ///    &lt;body&gt;
        ///  &lt;style&gt;
        ///* {
        ///  margin: 10;
        ///  padding: 5;
        ///}
        ///
        ///dt {
        ///  display: block;
        ///  float: left;
        ///  width: 175px;
        ///  text-align: right;
        ///  font-weight: bold;
        ///}
        ///
        ///dt:after {
        ///  content: &apos;: &apos;;
        ///}
        ///
        ///dd {
        ///  display: block;
        ///  margin-left: 190px;
        ///}
        ///&lt;/style&gt;
        ///
        ///  	
        ///	&lt;h3&gt;Marquesas Javascript Examples&lt;/h3&gt;
        ///	
        ///      &lt;p&gt;
        ///      &lt;select i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_Example_Usage {
            get {
                return ResourceManager.GetString("HTML_Example_Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html lang=&quot;en&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///  &lt;title&gt;&lt;!-- ApplicationName --&gt; Index&lt;/title&gt;
        ///  &lt;link rel=&quot;stylesheet&quot; href=&quot;https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css&quot;&gt;
        ///  &lt;script src=&quot;https://code.jquery.com/jquery-3.2.1.min.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script src=&quot;https://code.jquery.com/ui/1.12.1/jquery-ui.js&quot;&gt;&lt;/script&gt;
        ///  &lt;script&gt;
        ///  $( function() {
        ///    $( &quot;#tabs&quot; ).tabs();
        ///  } );
        ///
        ///  $( function()  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_Index {
            get {
                return ResourceManager.GetString("HTML_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot;
        ///content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///&lt;title&gt;Game Manual&lt;/title&gt;
        ///
        ///&lt;script src=&quot;https://code.jquery.com/jquery-3.2.1.min.js&quot; integrity=&quot;sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=&quot; crossorigin=&quot;anonymous&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div id=&quot;pdf&quot; style=&quot;width:100%;height:100%&quot;&gt;&lt;/div&gt;
        ///
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///
        ///var oTimer = null;
        ///var sID = null
        ///
        ///function refresh() {
        ///document.getElementById(&quot;pdf&quot;).innerHTML = &quot;&lt;e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_Manual {
            get {
                return ResourceManager.GetString("HTML_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;refresh&quot; content=&quot;&lt;!-- SecondsBetweenRefresh --&gt;&quot;&gt;&lt;/head&gt;&lt;body&gt;&lt;div class=&apos;bgSizeContain&apos;&gt;&lt;/div&gt;&lt;style&gt;html, body {margin:0;padding:0;height:100%;background-color:black} .bgSizeContain { height: 100%; width: 100%; background-image: url(&lt;!-- Base64Image --&gt;); background-repeat: no-repeat;  background-position: center; background-size: contain; &lt;/style&gt;&lt;/body&gt;&lt;/html&gt;.
        /// </summary>
        internal static string HTML_Marque {
            get {
                return ResourceManager.GetString("HTML_Marque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;refresh&quot; content=&quot;&lt;!-- SecondsBetweenRefresh --&gt;&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div
        ///style=&quot;border: 2px dashed rgb(246, 156, 85); text-align: center; height: 480px; line-height: 480px;&quot;&gt;&lt;big
        ///style=&quot;text-decoration: underline;&quot;&gt;&lt;big style=&quot;font-weight: bold;&quot;&gt;&lt;big&gt;&lt;big&gt;No
        ///game currently selected&lt;/big&gt;&lt;/big&gt;&lt;/big&gt;&lt;/big&gt;
        ///&lt;/div&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string HTML_NoGame {
            get {
                return ResourceManager.GetString("HTML_NoGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;&lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;refresh&quot; content=&quot;&lt;!-- SecondsBetweenRefresh --&gt;&quot;&gt;
        ///
        ///&lt;style&gt;
        ///div {
        ///display: table;
        ///height: 100px;
        ///width: 100%;
        ///text-align: center;
        ///border: 2px dashed #f69c55;
        ///}
        ///span {
        ///display: table-cell;
        ///vertical-align: middle;
        ///}
        ///&lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///&lt;div&gt;&lt;span&gt;&lt;big style=&quot;text-decoration: underline;&quot;&gt;&lt;big
        ///style=&quot;font-weight: bold;&quot;&gt;&lt;big&gt;&lt;big&gt;Resource not available&lt;/big&gt;&lt;/big&gt;&lt;/big&gt;&lt;/big&gt;&lt;br&gt;
        ///Title:&lt;!-- Title --&gt; &lt;br&gt;
        ///Path:&lt;!-- Path --&gt; &lt;br&gt;
        ///&lt;/span&gt;&lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_NoResource {
            get {
                return ResourceManager.GetString("HTML_NoResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon_16x16 {
            get {
                object obj = ResourceManager.GetObject("icon_16x16", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_original {
            get {
                object obj = ResourceManager.GetObject("icon_original", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string ServerStatus_Running {
            get {
                return ResourceManager.GetString("ServerStatus_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This may be due to a network issue, a configuration issue, lack of file permissions, or a too out of date plugin that can not be auto updated. If this error persists please update manually by downloading the latest version from https://forums.launchbox-app.com/files/file/675-marquesas-http-server or https://github.com/fpdavis/MarquesasServer/releases.
        /// </summary>
        internal static string UpdateError {
            get {
                return ResourceManager.GetString("UpdateError", resourceCulture);
            }
        }
    }
}
